# Quick start, sudoku example

If you want to run this on your local machine, make sure to install CPMpy first:

    pip3 install cpmpy
    
## Loading the libraries


In [1]:
# load the libraries
import numpy as np
from cpmpy import *

## A sudoku puzzle

Sudoku is a logic-based number puzzle, played on a partially filled 9x9 grid. The goal is to find the unique solution by filling in the empty grid cells with numbers from 1 to 9 in such a way that each row, each column and each of the nine 3x3 subgrids contain all the numbers from 1 to 9 once and only once.

We now define an example 9x9 puzzle, with some grid cells given and some empty:

In [2]:
e = 0 # value for empty cells
given = np.array([
    [e, e, 2,  4, 1, e,  e, e, 5],
    [1, e, 4,  3, e, e,  e, e, e],
    [e, 8, e,  2, 7, 5,  3, 4, 1],

    [e, e, e,  e, 3, 1,  e, e, e],
    [7, 9, e,  e, e, e,  e, 2, e],
    [e, e, e,  e, e, e,  e, e, e],

    [e, e, e,  e, e, 4,  e, 6, e],
    [5, e, e,  8, e, e,  4, e, 9],
    [e, 4, e,  1, e, 3,  5, 7, e]])

Note how we use `e` to represent the empty cells, where `e` is a standard python variable that we gave value `0`, e.g. the cells with a `0` value are the ones we seek.

## Variables and domains
Let's have a look at the problem description again:

* The goal is to find the unique solution by filling in the empty grid cells with numbers from 1 to 9
    
We will model this with Integer Decision Variables with a value of at least 1 and at most 9, arranged in a matrix just like the given puzzle:

In [ ]:
model = Model()

# Variables
puzzle = intvar(1, 9, shape=given.shape, name="puzzle")

# Constraints on rows and columns
model += [AllDifferent(row) for row in puzzle]
model += [AllDifferent(col) for col in puzzle.T]

# Constraints on blocks
for i in range(0,9, 3):
    for j in range(0,9, 3):
        model += AllDifferent(puzzle[i:i+3, j:j+3])

# Constraints on values (cells that are not empty)
model += (puzzle[given!=e] == given[given!=e])


model.solve()

In [3]:
# Variables
puzzle = intvar(1, 9, shape=given.shape, name="puzzle")

## Modeling the constraints

* each row, 
* each column and
* each of the nine 3x3 subgrids contain all the numbers from 1 to 9 once and only once.

We will use the `AllDifferent()` global constraint for this.

In [4]:
# we create a model with the row/column constraints
model = Model(
    # Constraints on rows and columns

)

# we extend it with the block constraints
# Constraints on blocks
for i in range(0,9, 3):
    for j in range(0,9, 3):
        model += AllDifferent(puzzle[i:i+3, j:j+3]) # python's indexing

# Constraints on values (cells that are not empty)
model += (puzzle[given!=e] == given[given!=e]) # numpy's indexing

The last constraint ensures that grid cells that are not empty (e.g. `given != e`) receive their given value.

## Solving

With the data, variables and constraints set, we can now combine these in a CP model, and use a solver to solve it:

In [5]:
# Solve and print
if model.solve():
    print(puzzle.value())
else:
    print("No solution found")

[[3 7 2 4 1 9 6 8 5]
 [1 5 4 3 8 6 2 9 7]
 [6 8 9 2 7 5 3 4 1]
 [2 6 8 9 3 1 7 5 4]
 [7 9 3 5 4 8 1 2 6]
 [4 1 5 6 2 7 9 3 8]
 [9 2 1 7 5 4 8 6 3]
 [5 3 7 8 6 2 4 1 9]
 [8 4 6 1 9 3 5 7 2]]


More examples can be found in the `examples/` folder.

Have fun!